name: Docker Build and Push to ghcr.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - run: echo "ğŸ‰ github.actor ${{ github.actor }}."
      - run: echo "ğŸ‰ secrets.GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}."
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ This job's status is ${{ job.status }}."

      - name: "ghcr.ioã«ãƒ­ã‚°ã‚¤ãƒ³ã™ã‚‹"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    # - name: "ãƒ¡ã‚¿ãƒ‡ãƒ¼ã‚¿ã‚’ä½œæˆã™ã‚‹"
    #   id: meta # å¾Œæ®µã§å‚ç…§ã§ãã‚‹ã‚ˆã†ã«outputsã«ç™»éŒ²ã™ã‚‹
    #   uses: docker/metadata-action@v5
    #   with:
    #     images: ghcr.io/yamakura-yuma/cloud-env-dev
    #     tags: |
    #       type=raw,value=latest
    #       type=sha,prefix=,suffix=,format=short

    #   - name: Build and push images
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: .
    #       file: ./.devcontainer/Dockerfile
    #       push: true
    #       tags: ${{ steps.meta.outputs.tags }} # å‰ã‚¹ãƒ†ãƒƒãƒ—ã§è¨­å®šã—ãŸã‚¿ã‚°ã‚’å‚ç…§ã™ã‚‹
    #       labels: ${{ steps.meta.outputs.labels }} # å‰ã‚¹ãƒ†ãƒƒãƒ—ã§è¨­å®šã—ãŸãƒ©ãƒ™ãƒ«ã‚’å‚ç…§ã™ã‚‹
